apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system  # donde vive el objeto HelmRelease
spec:
  targetNamespace: kube-system
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: cilium
    namespace: flux-system
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
    remediation:
      retries: 3
      strategy: rollback
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values
      valuesKey: values.yaml
