apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: proxmox
  namespace: scrape-configs
  labels:
    prometheus: system-monitoring-prometheus
spec:
  metricsPath: /pve
  params:
    module: [default]
    target: ["192.168.1.2"]
  staticConfigs:
    - targets:
        - 192.168.1.2:9221
      labels:
        job: proxmox
