resources:
  - ./helmrelease.yaml
  - ./ocirepository.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: kube-prometheus-stack-values
    namespace: monitoring
    files:
      - values.yaml

