apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-issuer-secret
    namespace: cert-manager
type: Opaque
stringData:
    CLOUDFLARE_DNS_TOKEN: ENC[AES256_GCM,data:VvgQu/C2Pn2T53GSTnk7T0J4qRJ2Uf/zYXZzvJBkXdC0cQCQWwBAPTOIDI7Hbu/oC/XR/10=,iv:D383c3K92Bh7zFCIubG3oaLEsTsHrC1yfrmfeq5I0Lk=,tag:5u4/tY397Xxsc7NmAvo8/Q==,type:str]
sops:
    age:
        - enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQVNpcEJjc09tV2JrNVdh
              V0RyNWpxa3Z1d0hRUjFFK0ZWMm1YY3hXYlFJCjA3bWNVT2hWeGtmSlg4blpwc005
              dEdvbXI5N2pJejRRQXR2NjZPbUpHQWcKLS0tIGZyQ3VsRmxZb3cwelNCWVNtMHZR
              V1ZjbExud0JCT3JQN3YzQnBMcmp5NFkKf1+niGiP2CaA1hlm3pa3cEjczVIZN+el
              +rdKMA8FjoZrWxnaupdfaPpJX2GWFsrCYUd4ftfipcip0V6D5GT4Gg==
              -----END AGE ENCRYPTED FILE-----
          recipient: age16vxlnzz0r3zgdm9l6t2scs9wpfule9xhcepv7vf5rwvl39pfvqssre0pju
    encrypted_regex: (?i)(token|secret)
    lastmodified: "2026-07-11T20:53:08Z"
    mac: ENC[AES256_GCM,data:UqimxUQTXZlkPD5rseyBo8aCKeAKVkReV3U5Y4O80MC8DSw3FUfvrgReswoE5nA2nR+gKSNVs/KqilddxCUYZjE8HCkGuAIniNshW9GqR/lLnONXybvEysJEzxoJy5bJPVNr5NhdXSFNxanEkph+81Oaw3coNYGrJkoVIll4rwo=,iv:lpOeX71O5VndqHwJO/2vFrjez8W7hoA9E15TSS+3hBk=,tag:krpmP7o465K9ubSHukDM2w==,type:str]
    version: 3.13.2
