apiVersion: v1
data:
  datasources.yaml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://monitoring-kube-prometheus-prometheus:9090
        jsonData:
          httpMethod: POST
          manageAlerts: true
          allowAsRecordingRulesTarget: true
          prometheusType: Prometheus
          prometheusVersion: 3.11.3
          cacheLevel: 'High'
          disableRecordingRules: false
          seriesEndpoint: false
          timeInterval: 10s
          incrementalQueryOverlapWindow: 10m
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
