apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/
  - ./datasources-configmap.yaml

patches:
  - path: ./pvc.yaml
  - path: ./deployment.yaml

images:
  - name: grafana/grafana
    newTag: latest
